server:
  port: 8080 # 服务器端口
  servlet:
    context-path: /api
spring:
  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定Mapper XML文件路径
  type-aliases-package: com.simple.pg.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰（如article_id → articleId）
    cache-enabled: false # 关闭全局缓存（生产可根据场景开启）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
# 日志配置
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE